apiVersion: v1
kind: Service               
metadata:
  name: go-math
spec:
  type: NodePort               
  ports:            
  - name: http
    port: 8080
    targetPort: 8010
  selector:
    app: go-math